#!/usr/bin/env python
"""Emit a download manifest for only the waveforms MDS-ED actually uses.

MIMIC-IV-ECG holds 800,035 records; MDS-ED references 129,057 of them, and its
`general_file_name` column pins each one exactly. Downloading the whole 33.8 GB
archive to use 16 percent of it wastes days of wall clock, and this stage is already the
binding constraint under local compute.

Writes three artifacts under ``$ECG_DATA_ROOT/derived/waveforms/``, never into
the repository, since the manifest is derived from credentialed data:

  ``curl_config.txt``   a curl `-K` config: url/output pairs, one connection reused
  ``urls.txt``          plain URL list for aria2c `-i`
  ``manifest.json``     counts, the record-set hash, and what it was derived from

Each record is two files: ``.hea`` (header) and ``.dat`` (signal).

    python scripts/make_waveform_manifest.py
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))

from contract import load_contract  # noqa: E402
from loaders import resolve_path  # noqa: E402
from paths import data_root, derived_root  # noqa: E402

BASE_URL = "https://physionet.org/files/mimic-iv-ecg/1.0"
SUFFIXES = (".hea", ".dat")


def _normalise(raw: str) -> str:
    text = str(raw).replace("\\", "/").strip()
    marker = "/files/"
    if marker in text:
        return "files/" + text.split(marker, 1)[1]
    if text.startswith("files/"):
        return text
    raise ValueError(
        f"unrecognised waveform path {raw!r}; expected a 'files/...' segment"
    )


def record_paths(root: Path, contract) -> tuple[list[str], dict[str, int]]:
    """Record stems MDS-ED references, ordered test fold first.

    PhysioNet rate-limits to roughly 5 requests per second regardless of client
    concurrency, so the full subset takes about 14 hours no matter how it is
    tuned. Order is therefore the only lever that matters: fetching the test fold
    first means the waveform pipeline can be validated end to end within the hour,
    and training data arrives while that is happening.
    """
    path = resolve_path("mds_ed.cohort", root, contract)
    frame = pd.read_csv(
        path, usecols=["general_file_name", "general_strat_fold"], low_memory=False
    )
    assignment = contract.raw["split"]["assignment"]
    priority = {"test": 0, "val": 1, "train": 2}
    fold_to_split = {
        int(fold): name for name, folds in assignment.items() for fold in folds
    }

    rows = []
    for raw, fold in zip(frame["general_file_name"], frame["general_strat_fold"]):
        if pd.isna(raw):
            continue
        split = fold_to_split.get(int(fold), "train")
        rows.append((priority.get(split, 2), int(fold), _normalise(raw), split))

    seen: set[str] = set()
    ordered: list[str] = []
    counts: dict[str, int] = {"test": 0, "val": 0, "train": 0}
    for _, _, stem, split in sorted(rows):
        if stem in seen:
            continue
        seen.add(stem)
        ordered.append(stem)
        counts[split] = counts.get(split, 0) + 1
    return ordered, counts


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data-root", default=None)
    parser.add_argument("--out", default=None)
    parser.add_argument("--quiet", action="store_true")
    args = parser.parse_args()

    contract = load_contract()
    root = data_root(args.data_root)
    target_root = (root / "mimic-iv-ecg").resolve()

    stems, split_counts = record_paths(root, contract)
    out = Path(args.out) if args.out else derived_root(args.data_root) / "waveforms"
    out.mkdir(parents=True, exist_ok=True)

    curl_lines: list[str] = [
        "# url/output pairs for the MDS-ED waveform subset, test fold first.",
        "# Generated by scripts/make_waveform_manifest.py. Do not edit.",
        "#",
        "# Fetch with:  python scripts/fetch_waveforms.py --workers 16",
        "#",
        "# Do NOT feed this to `curl -K`: curl does not pair `output` with `url`",
        "# positionally inside a config file, it collapses them to one global -o and",
        "# writes a single file. This file is consumed by fetch_waveforms.py, which",
        "# pairs them correctly, retries, and resumes.",
        "",
    ]
    urls: list[str] = []
    for stem in stems:
        for suffix in SUFFIXES:
            url = f"{BASE_URL}/{stem}{suffix}"
            # Forward slashes, always. curl's config parser treats a backslash as
            # an escape character, so a Windows-style path silently mangles into
            # nonsense ("\U", "\p") and every write fails. Windows accepts POSIX
            # separators, so this is correct on both platforms.
            destination = (target_root / Path(stem + suffix)).as_posix()
            urls.append(url)
            curl_lines.append(f'url = "{url}"')
            curl_lines.append(f'output = "{destination}"')

    (out / "curl_config.txt").write_text("\n".join(curl_lines) + "\n", encoding="utf-8")
    (out / "urls.txt").write_text("\n".join(urls) + "\n", encoding="utf-8")

    digest = hashlib.sha256("\n".join(stems).encode("utf-8")).hexdigest()
    (out / "manifest.json").write_text(
        json.dumps(
            {
                "n_records": len(stems),
                "n_files": len(urls),
                "files_per_record": list(SUFFIXES),
                "base_url": BASE_URL,
                "target_root": str(target_root),
                "record_set_sha256": digest,
                "records_by_split": split_counts,
                "order": "test fold first, then validation, then train",
                "derived_from": "mds_ed.csv general_file_name",
                "note": "MIMIC-IV-ECG holds 800,035 records; MDS-ED references "
                        f"{len(stems)}. Downloading only these is the difference "
                        "between hours and days.",
            },
            indent=2,
        ),
        encoding="utf-8",
    )

    if not args.quiet:
        share = len(stems) / 800_035
        print(f"manifest root: {out}")
        print(f"  records      {len(stems):>9,}  ({share:.1%} of MIMIC-IV-ECG's 800,035)")
        print(f"  files        {len(urls):>9,}  (.hea + .dat per record)")
        print(f"  target       {target_root}")
        print(f"  record set   sha256 {digest[:16]}")
        print("  order        test fold first, then val, then train:")
        for name in ("test", "val", "train"):
            n = split_counts.get(name, 0)
            print(f"                 {name:<6} {n:>7,} records  ({2*n:>7,} files, "
                  f"~{2*n/5.0/3600:5.2f} h at the observed 5 files/s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
