#!/usr/bin/env python
"""Generate notes/feature_dictionary.md from the source-schema contract.

The dictionary is generated rather than written, for the same reason the results
tables are: a hand-maintained dictionary drifts from the pipeline silently, and
the one place that must never be wrong about which block a feature belongs to is
the document a reviewer reads when checking the leakage claim.

Missingness rates are filled from a built feature table when one exists, and are
otherwise reported as pending. They are never estimated.

    python scripts/make_dictionary.py
    python scripts/make_dictionary.py --features <path to features_acq.parquet>
"""

from __future__ import annotations

import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from contract import load_contract  # noqa: E402
from paths import REPO_ROOT, derived_root  # noqa: E402

BLOCK_TITLES = {
    "demographics": ("Demographics", "Row 2 baseline. Not part of the audit claim."),
    "acq_pre": (
        "ACQ_PRE — confirmatory block",
        "Fixed at or before the index acquisition. Row 3 uses this block and "
        "nothing else. Every column here is checked by `scripts/leakage_test.py`.",
    ),
    "acq_window": (
        "ACQ_WINDOW — leakage-suspect block",
        "Resolves after the index acquisition. Never enters a confirmatory arm. "
        "Reported only as row 3b, and a gain over row 3 is a leakage measurement "
        "rather than a finding about triage behaviour.",
    ),
}


def missingness(features_path: Path | None) -> dict[str, str]:
    if not features_path or not features_path.is_file():
        return {}
    import pandas as pd

    frame = pd.read_parquet(features_path)
    return {
        column: f"{frame[column].isna().mean():.1%}"
        for column in frame.columns
        if not column.startswith("available_at__")
    }


def render(contract, rates: dict[str, str], source_label: str) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%MZ")
    lines = [
        "# feature_dictionary.md",
        "",
        "Generated by `scripts/make_dictionary.py` from `configs/source_schema.yaml`.",
        "Never hand-edited: edit the contract and regenerate, so the dictionary and",
        "the pipeline cannot disagree about which block a feature is in.",
        "",
        f"- Generated: {now}",
        f"- Contract sha256: `{contract.sha256}`",
        f"- Missingness source: {source_label}",
        "",
        "Every row states source table and column, transformation, the rule that",
        "decides the feature's availability timestamp, and its leakage status, as",
        "the project's design notes the protocol requires.",
        "",
    ]

    for block in ("demographics", "acq_pre", "acq_window"):
        title, blurb = BLOCK_TITLES[block]
        derivations = contract.block(block)
        lines += [f"## {title}", "", blurb, ""]
        lines += [
            "| Feature | Source | Transformation | Availability rule | Available at | dtype | Missingness | Leakage status |",
            "|---|---|---|---|---|---|---|---|",
        ]
        for derivation in derivations:
            if block == "acq_pre":
                status = "safe by construction; asserted per row"
            elif block == "acq_window":
                status = f"**suspect** — {derivation.leakage_risk}"
            else:
                status = "not applicable"
            if derivation.availability == "unverified":
                status += " (availability unverified, the unverified over-read flag)"
            lines.append(
                "| `{name}` | {source} | {transform} | `{rule}` | {stamp} | {dtype} | {miss} | {status} |".format(
                    name=derivation.name,
                    source="<br>".join(f"`{s}`" for s in derivation.source),
                    transform=derivation.transform.strip().replace("\n", " "),
                    rule=derivation.available_at,
                    stamp={
                        "ed_arrival_time": "ED arrival",
                        "index_time": "index acquisition",
                        "window_close": "arrival + 90 min",
                    }[derivation.available_at],
                    dtype=derivation.dtype,
                    miss=rates.get(derivation.name, "pending data access"),
                    status=status,
                )
            )
        lines.append("")

    lines += [
        "## Availability rules",
        "",
        "| Rule | Timestamp | Fixed at or before the index acquisition |",
        "|---|---|---|",
        "| `ed_arrival_time` | `edstays.intime` | yes |",
        "| `index_time` | the index ECG's `ecg_time` | yes |",
        "| `window_close` | `edstays.intime + 90 min` | **no** |",
        "",
        "Each emitted feature `X` carries a companion column `available_at__X`",
        "holding that timestamp per row. The guard asserts",
        "`available_at__X <= index_time` for every ACQ_PRE feature and treats a",
        "null stamp on a non-null value as a violation, not as a pass.",
        "",
        "## Open items affecting this dictionary",
        "",
        "| Item | Effect | Closes |",
        "|---|---|---|",
        "| the unverified over-read flag | `cardiologist_overread_exists` may not exist in MIMIC-IV-ECG. "
        "`build_features.py --probe-availability` decides, and drops it if no "
        "non-degenerate marker column is found. | at data access |",
        "| the declared outcome and horizon set | Label ids and horizons are provisional, so the cohort this "
        "dictionary is measured on is provisional too. | before the falsification test |",
        "| `triage_acuity` | Recorded at triage, whose timestamp MIMIC-IV-ED's "
        "`triage` table does not carry. Stamped at ED arrival as a documented "
        "lower bound, not as an observed time. | at data access |",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--features", default=None)
    parser.add_argument("--out", default=None)
    parser.add_argument("--quiet", action="store_true")
    args = parser.parse_args()

    contract = load_contract()

    path = Path(args.features) if args.features else None
    if path is None:
        try:
            candidate = derived_root() / "features_acq.parquet"
            path = candidate if candidate.is_file() else None
        except RuntimeError:
            path = None

    rates = missingness(path)
    label = str(path) if rates else "not yet measured; no feature table built"

    target = Path(args.out) if args.out else REPO_ROOT / "notes" / "feature_dictionary.md"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(render(contract, rates, label), encoding="utf-8")
    if not args.quiet:
        total = sum(len(contract.block(b)) for b in ("demographics", "acq_pre", "acq_window"))
        print(f"wrote {target} ({total} features)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
