#!/usr/bin/env python
"""Register row 8: the waveform arm evaluated with acquisition context held fixed.

Row 8 trains nothing. It is `R6_waveform`, unchanged, evaluated under the within-stratum specification's
within-stratum concordance, so there is one R8 run per R6 seed and each inherits
that seed's predictions. Registering it as a run anyway is the point of the
ledger: the arm differs from row 6 in its declared cohort, that difference is in
the resolved config, and the number it produces has to be as traceable as any
other.

    python scripts/run_matched_arm.py --seed 0
    python scripts/run_matched_arm.py --all
"""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
import time
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))

from contract import load_base_config  # noqa: E402
from paths import REPO_ROOT, derived_root  # noqa: E402
from run_arm import GENERATED_DIR, assert_declared, source_dirty  # noqa: E402
from score_arms import _waveform_seed_frame, ledger_index  # noqa: E402
from stratified import StratifiedConcordance, selftest  # noqa: E402

ARM = "R8_waveform_matched"
SOURCE_ARM = "R6_waveform"
COMPARISON = "acq_context_audit"


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def write_overlay(seed: int) -> Path:
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    path = GENERATED_DIR / f"{ARM}__all15__seed{seed}.yaml"
    path.write_text(
        "# Generated by scripts/run_matched_arm.py. Row 8 is row 6 evaluated on the\n"
        "# availability-matched cohort; the model is identical and the cohort is\n"
        "# not, so the cohort is what distinguishes the resolved config.\n"
        f"arm: {ARM}\n"
        f"comparison: {COMPARISON}\n"
        "label_active: all15\n"
        "data:\n"
        "  cohort: availability_matched\n"
        "  matching_specification: The within-stratum specification\n"
        "  matching_variables: [delay_bucket, hour_bucket, is_weekend, acuity_level]\n"
        "evaluation:\n"
        "  statistic: within_stratum_concordance\n"
        "training:\n"
        f"  seed: {seed}\n",
        encoding="utf-8",
    )
    return path


def register(seed: int, overlay: Path, split_file: Path) -> str:
    result = subprocess.run(
        [
            sys.executable, "scripts/ledger.py", "new",
            "--config", "configs/base.yaml",
            "--overlay", f"configs/arms/{ARM}.yaml",
            "--overlay", str(overlay.relative_to(REPO_ROOT)).replace("\\", "/"),
            "--tag", f"arm={ARM}", "--tag", "label=all15", "--tag", f"seed={seed}",
            "--tag", f"comparison={COMPARISON}", "--tag", f"group={ARM}__all15",
            "--tag", "modality=waveform", "--tag", "cohort=availability_matched",
            "--split", str(split_file),
            "--entrypoint", "scripts/run_matched_arm.py",
            "--quiet", "--force",
        ],
        capture_output=True, text=True, cwd=str(REPO_ROOT),
    )
    if result.returncode != 0:
        raise RuntimeError(f"ledger new failed:\n{result.stdout}{result.stderr}")
    return result.stdout.strip().splitlines()[-1].strip()


def build(seed: int, labels: list[str], derived: Path) -> tuple[pd.DataFrame, dict]:
    """Row 6's seed-`seed` record-level scores, annotated with their stratum."""
    strata = pd.read_parquet(derived / "matched_strata.parquet")[
        ["study_id", "stratum"]
    ]
    index = ledger_index()
    run_id = index.get((SOURCE_ARM, "all15", seed))
    if run_id is None:
        raise RuntimeError(f"no registered {SOURCE_ARM} run at seed {seed}")

    frames, metrics = [], {}
    for label in labels:
        frame = _waveform_seed_frame(run_id, derived, label)
        frame = frame.merge(strata, on="study_id", how="inner")
        concordance = StratifiedConcordance(
            frame["y_true"].to_numpy(), frame["y_score"].to_numpy(),
            frame["stratum"].to_numpy(),
        )
        rows = np.arange(len(frame))
        informative = concordance.informative()
        keep = informative[concordance.codes]
        metrics[f"auroc_stratified__{label}"] = float(concordance.evaluate(rows))
        metrics[f"n_pairs__{label}"] = int(concordance.n_pairs())
        metrics[f"n_strata_informative__{label}"] = int(informative.sum())
        metrics[f"n_patients_effective__{label}"] = int(
            frame.loc[keep, "subject_id"].nunique()
        )
        frame["label"] = label
        frame["informative_stratum"] = keep
        frames.append(frame)

    metrics["source_run_id_is_r6_seed"] = seed
    return pd.concat(frames, ignore_index=True), metrics


def run_one(seed: int, labels: list[str], derived: Path, quiet: bool) -> str:
    started = time.time()
    frame, metrics = build(seed, labels, derived)

    overlay = write_overlay(seed)
    run_id = register(seed, overlay, derived / "split_published.parquet")

    pred_dir = derived / "predictions"
    pred_dir.mkdir(parents=True, exist_ok=True)
    pred_path = pred_dir / f"{run_id}.parquet"
    frame.to_parquet(pred_path, index=False)

    dirty, offenders = source_dirty()
    metrics["source_dirty"] = int(dirty)
    metrics["auroc"] = metrics[f"auroc_stratified__{labels[-1]}"]
    metrics["n_test_items"] = int(len(frame))
    metrics["n_test_groups"] = int(frame["subject_id"].nunique())
    metrics["n_test_positives"] = int(frame["y_true"].sum())
    metrics["fit_seconds"] = round(time.time() - started, 2)

    run_dir = REPO_ROOT / "runs" / run_id
    run_dir.mkdir(parents=True, exist_ok=True)
    (run_dir / "metrics.json").write_text(json.dumps(metrics, indent=2),
                                          encoding="utf-8")
    (run_dir / "predictions.pointer.json").write_text(
        json.dumps({
            "path": str(pred_path), "sha256": _sha256(pred_path),
            "n_rows": int(len(frame)),
            "note": "Row 6's record-level scores annotated with their the within-stratum specification "
                    "stratum. Row-level, so outside the repository.",
        }, indent=2), encoding="utf-8")
    (run_dir / "provenance.json").write_text(
        json.dumps({
            "source_dirty": bool(dirty), "source_dirty_paths": sorted(offenders),
            "derives_from": f"{SOURCE_ARM} seed {seed}",
            "note": "Row 8 trains nothing. It is row 6 under the within-stratum specification's within-stratum "
                    "statistic, so its predictions are row 6's and only the "
                    "evaluation differs.",
        }, indent=2), encoding="utf-8")

    result = subprocess.run(
        [sys.executable, "scripts/ledger.py", "record", "--run", run_id,
         "--metrics", f"runs/{run_id}/metrics.json"],
        capture_output=True, text=True, cwd=str(REPO_ROOT),
    )
    if result.returncode != 0:
        raise RuntimeError(f"ledger record failed:\n{result.stdout}{result.stderr}")

    if not quiet:
        print(f"{run_id}  {ARM} seed={seed}  "
              + "  ".join(f"{l.replace('deterioration_', '')}="
                          f"{metrics[f'auroc_stratified__{l}']:.4f}" for l in labels))
    else:
        print(run_id)
    return run_id


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--seed", type=int)
    parser.add_argument("--all", action="store_true")
    parser.add_argument("--data-root", default=None)
    parser.add_argument("--quiet", action="store_true")
    args = parser.parse_args()

    problems = selftest()
    if problems:
        for line in problems:
            print(f"stratified selftest: {line}", file=sys.stderr)
        return 1

    base = load_base_config()
    labels = list(base["labels"])
    derived = derived_root(args.data_root)
    assert_declared(COMPARISON, ARM, labels[0])

    if not (derived / "matched_strata.parquet").is_file():
        print("matched_strata.parquet is missing; run scripts/build_matched_cohort.py",
              file=sys.stderr)
        return 1

    seeds = list(base["training"]["seeds"]) if args.all else [args.seed]
    if seeds == [None]:
        print("give --seed or --all", file=sys.stderr)
        return 2
    for seed in seeds:
        run_one(int(seed), labels, derived, args.quiet)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
