#!/usr/bin/env python
"""Train one waveform arm for one seed and register it in the ledger.

The waveform counterpart of `run_arm.py`, and deliberately the same shape: one
generated config per (arm, seed) so run ids differ, tagged to the declared
comparison, registered before the run and recorded after it, with predictions
written outside the repository behind a hashed pointer.

Two things differ from the tabular path, both forced by the arm rather than
chosen. The model is multi-label over all 15 deterioration targets, so one run
produces one metrics file covering every target rather than one run per label;
`label=all15` is the tag. And every run records peak VRAM and wall clock, which
the project's design notes the protocol requires and which a CPU arm has no analogue of.

    python scripts/run_waveform_arm.py --arm R6_waveform --seed 0
    python scripts/run_waveform_arm.py --arm R6_waveform --seed 0 --resume
    python scripts/run_waveform_arm.py --arm R6_waveform --seed 0 --max-hours 7
"""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from contract import load_base_config  # noqa: E402
from paths import REPO_ROOT, derived_root  # noqa: E402
from run_arm import GENERATED_DIR, _sha256, source_dirty  # noqa: E402

WAVEFORM_ARMS = ("R6_waveform", "R7_waveform_demo_acq")
LABEL_TAG = "all15"


def write_overlay(arm: str, seed: int) -> Path:
    """One committed config per run, so the resolved config hash is distinct."""
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    path = GENERATED_DIR / f"{arm}__{LABEL_TAG}__seed{seed}.yaml"
    path.write_text(
        "# Generated by scripts/run_waveform_arm.py. One file per (arm, seed) so the\n"
        "# resolved config, and therefore the run_id, is distinct per seed.\n"
        "# The waveform arm is multi-label over all 15 deterioration targets in one\n"
        "# model, so there is no per-label config here.\n"
        f"arm: {arm}\n"
        f"label_active: {LABEL_TAG}\n"
        "training:\n"
        f"  seed: {seed}\n",
        encoding="utf-8",
    )
    return path


def register(arm: str, seed: int, overlay: Path, split_file: Path) -> str:
    result = subprocess.run(
        [
            sys.executable, "scripts/ledger.py", "new",
            "--config", "configs/base.yaml",
            "--overlay", f"configs/arms/{arm}.yaml",
            "--overlay", str(overlay.relative_to(REPO_ROOT)).replace("\\", "/"),
            "--tag", f"arm={arm}", "--tag", f"label={LABEL_TAG}", "--tag", f"seed={seed}",
            "--tag", "comparison=acq_context_audit",
            "--tag", f"group={arm}__{LABEL_TAG}",
            "--tag", "modality=waveform",
            "--split", str(split_file),
            "--entrypoint", "scripts/run_waveform_arm.py",
            "--quiet", "--force",
        ],
        capture_output=True, text=True, cwd=str(REPO_ROOT),
    )
    if result.returncode != 0:
        raise RuntimeError(f"ledger new failed:\n{result.stdout}{result.stderr}")
    return result.stdout.strip().splitlines()[-1].strip()


def flatten_metrics(summary: dict, test: dict) -> dict:
    """`ledger record` takes numeric values only, so everything here is a number."""
    metrics: dict[str, float] = {
        "auroc_macro_crop": test["crop_level"]["macro"],
        "auroc_macro_record": test["record_level"]["macro"],
        "n_targets_scored": test["crop_level"]["n_targets_scored"],
        "n_crop_rows": test["n_crop_rows"],
        "n_record_rows": test["n_record_rows"],
        "n_test_groups": test["n_patients"],
        "best_val_macro": summary["best_val_macro"],
        "epochs_completed": summary["epochs_completed"],
        "epochs_configured": summary["epochs_configured"],
        "wall_seconds": summary["wall_seconds"],
        "gpu_hours": summary["gpu_hours"],
        "peak_vram_mib": summary["peak_vram_mib"],
        "median_epoch_seconds": summary["median_epoch_seconds"] or 0.0,
        "batch_size": summary["batch_size"],
        "lr": summary["lr"],
        "dropout": summary["dropout"],
        "crop_samples": summary["crop_samples"],
        "static_dim": summary["static_dim"],
        "n_train_records": summary["n_train_records"],
        "memmap_complete": int(bool(summary.get("memmap_complete", False))),
    }
    # Per-target AUROC under both protocols. The macro is a mean over these, and
    # a reader must be able to see which targets carry its variance.
    for unit in ("crop_level", "record_level"):
        for name, value in test[unit]["per_target"].items():
            key = f"auroc_{'crop' if unit == 'crop_level' else 'record'}__{name}"
            metrics[key] = value
    return metrics


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--arm", required=True, choices=WAVEFORM_ARMS)
    parser.add_argument("--seed", type=int, required=True)
    parser.add_argument("--max-hours", type=float, default=0.0)
    parser.add_argument("--resume", action="store_true")
    parser.add_argument("--epochs", type=int, default=None)
    parser.add_argument("--data-root", default=None)
    parser.add_argument("--dry-run", action="store_true",
                        help="report what would run, register nothing")
    parser.add_argument("--allow-untuned", action="store_true",
                        help="train without a tuning result; breaks A4's equal budget")
    args = parser.parse_args()

    base = load_base_config()
    derived = derived_root(args.data_root)

    dirty, offenders = source_dirty()
    if dirty and not args.dry_run:
        # this, not the ledger's own git_dirty, is the real check. A batch
        # launched from a modified tree cannot be rebuilt from its recorded commit.
        print("REFUSING: source tree is dirty. Commit before launching a batch.",
              file=sys.stderr)
        for path in offenders[:20]:
            print(f"  {path}", file=sys.stderr)
        return 2

    ckpt_dir = derived / "checkpoints" / f"{args.arm}__seed{args.seed}"
    if args.dry_run:
        print(f"would train {args.arm} seed={args.seed} into {ckpt_dir}")
        return 0

    # The tuned configuration, if the search has run. Both arms get their own
    # search of the same size, so reading it here is what makes
    # "equal budget" true rather than merely declared.
    tuned_path = derived / "tuning" / f"{args.arm}__all15.json"
    tuned = None
    if tuned_path.is_file():
        tuned = json.loads(tuned_path.read_text(encoding="utf-8"))["winner"]
        print(f"using tuned config {tuned['id']}: lr={tuned['lr']} dropout={tuned['dropout']}")
    elif not args.allow_untuned:
        print(
            f"REFUSING: no tuning result at {tuned_path}. Training this arm now would "
            "give it a different budget from the other, which the project's design notes the protocol forbids in "
            "either direction. Run `python scripts/run_p2.py --stage tune` first, or "
            "pass --allow-untuned and expect to justify it.",
            file=sys.stderr,
        )
        return 2

    started = time.time()
    cmd = [
        sys.executable, "scripts/train/train_waveform.py",
        "--arm", args.arm, "--seed", str(args.seed), "--out", str(ckpt_dir),
    ]
    if tuned:
        cmd += ["--lr", str(tuned["lr"]), "--dropout", str(tuned["dropout"])]
    if args.max_hours:
        cmd += ["--max-hours", str(args.max_hours)]
    if args.epochs is not None:
        cmd += ["--epochs", str(args.epochs)]
    if args.resume:
        cmd.append("--resume")
    result = subprocess.run(cmd, cwd=str(REPO_ROOT))
    if result.returncode != 0:
        print(f"training exited {result.returncode}; nothing registered", file=sys.stderr)
        return result.returncode

    summary = json.loads((ckpt_dir / "train_summary.json").read_text(encoding="utf-8"))
    test = json.loads((ckpt_dir / "test_metrics.json").read_text(encoding="utf-8"))

    # The selected configuration can change between a run starting and finishing:
    # The tuning tie-break rule's tie-break was declared while R6 seed 0 was ten epochs into training
    # at the previous winner's dropout, and nothing would have stopped that run
    # being registered as the reproduction. A run whose hyperparameters are not
    # the currently selected ones is not the run the ledger would claim it is.
    if tuned:
        drift = [
            (name, summary.get(name), tuned.get(name))
            for name in ("lr", "dropout")
            if abs(float(summary.get(name, 0)) - float(tuned.get(name, 0))) > 1e-12
        ]
        if drift:
            detail = ", ".join(f"{n}: trained {a} vs selected {b}" for n, a, b in drift)
            print(
                f"REFUSING to register {args.arm} seed {args.seed}: the completed run "
                f"does not match the selected configuration ({detail}). The selection "
                "changed after this run started. Move the checkpoint aside and retrain.",
                file=sys.stderr,
            )
            return 4
    if summary["epochs_completed"] < summary["epochs_configured"]:
        # A wall-clock stop is legitimate but must never be invisible: the run is
        # registered with the epochs it actually completed and a reader can see
        # it was truncated.
        print(f"NOTE: run stopped after {summary['epochs_completed']} of "
              f"{summary['epochs_configured']} epochs ({summary['stopped_early']})")

    overlay = write_overlay(args.arm, args.seed)
    split_file = derived / "split_published.parquet"
    run_id = register(args.arm, args.seed, overlay, split_file)

    # Predictions are keyed by subject_id, so they live outside the repo.
    pred_dir = derived / "predictions"
    pred_dir.mkdir(parents=True, exist_ok=True)
    pred_path = pred_dir / f"{run_id}.npz"
    pred_path.write_bytes((ckpt_dir / "test_predictions.npz").read_bytes())

    run_dir = REPO_ROOT / "runs" / run_id
    run_dir.mkdir(parents=True, exist_ok=True)
    (run_dir / "predictions.pointer.json").write_text(
        json.dumps({
            "path": str(pred_path),
            "sha256": _sha256(pred_path),
            "n_rows": int(test["n_record_rows"]),
            "n_crop_rows": int(test["n_crop_rows"]),
            "format": "npz",
            "arrays": ["crop_scores", "crop_y", "crop_mask", "crop_local", "crop_index",
                       "record_scores", "record_y", "record_mask",
                       "subject_id", "study_id", "targets"],
            "note": "Row-level predictions are keyed by subject_id and are kept outside "
                    "the repository under $ECG_DATA_ROOT. Both the crop-level scores the "
                    "published protocol uses and the record-level scores every cross-arm "
                    "contrast uses are stored, so either analysis rebuilds from one "
                    "artifact. See the containment rule, the row-level data rule, the crop-level and record-level separation.",
        }, indent=2),
        encoding="utf-8",
    )

    metrics = flatten_metrics(summary, test)
    metrics["source_dirty"] = int(dirty)
    metrics["total_seconds_including_scoring"] = round(time.time() - started, 1)
    (run_dir / "metrics.json").write_text(json.dumps(metrics, indent=2), encoding="utf-8")
    (run_dir / "provenance.json").write_text(
        json.dumps({
            "source_dirty": bool(dirty),
            "source_dirty_paths": sorted(offenders),
            "preprocess_hash": summary["preprocess_hash"],
            "content_hash": summary.get("content_hash", ""),
            "memmap_complete": summary.get("memmap_complete"),
            "gpu_model": summary["gpu_model"],
            "torch": summary["torch"],
            "static_columns": summary.get("static_columns", []),
            "history": summary["history"],
            "stopped_early": summary["stopped_early"],
            "note": "See the source-dirty rule for why source_dirty is recorded rather than the "
                    "ledger's own git_dirty flag.",
        }, indent=2),
        encoding="utf-8",
    )
    (run_dir / "train_summary.json").write_text(json.dumps(summary, indent=2), encoding="utf-8")

    result = subprocess.run(
        [sys.executable, "scripts/ledger.py", "record", "--run", run_id,
         "--metrics", f"runs/{run_id}/metrics.json"],
        capture_output=True, text=True, cwd=str(REPO_ROOT),
    )
    if result.returncode != 0:
        raise RuntimeError(f"ledger record failed:\n{result.stdout}{result.stderr}")

    print(f"{run_id}  {args.arm:<22} seed={args.seed}  "
          f"macro(crop)={metrics['auroc_macro_crop']:.4f}  "
          f"macro(record)={metrics['auroc_macro_record']:.4f}  "
          f"{metrics['gpu_hours']:.2f} GPU-h  {metrics['peak_vram_mib']:.0f} MiB")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
