"""The one place that maps a table's PANEL ID to its DISPLAY LABEL.

`notes/table_layout.md` has said since this stage that "every number in `paper/` points
at a table by its generated id, `T4b` and so on, and those ids do not change
when a panel moves between the two lists. Renumbering for the venue is
`submission-formatter`'s pass, and it changes display labels only."

Until this stage the two were the same string, so nothing had to say which was which.
this stage added a table that is not generated by `make_table_main.py`, the
related-work summary, put it in the Background ahead of every results panel,
and shifted every generated label by one. this stage moved that table out of the main
text and shifted them back.

Both of those were arithmetic on one sequence shared by the manuscript and the
supplement, and that sharing was itself the defect. The main text cited Tables
1, 2, 3, 4b, 4d, 6a, 8, 9 and 10: the gaps are the panels that ship in the
supplement, and a reader has no way to know that. So the sequence is split.
The manuscript numbers its own tables 1 to 9 in the order the prose first
cites them, the supplement numbers its own S1 to S12, and neither can renumber
the other.

That makes the map arbitrary rather than derivable, which is why it is written
out below instead of computed. A panel added later has to be given a label
here, deliberately, and the corresponding check fails on any heading or prose
reference that resolves to none.
"""

from __future__ import annotations

#: Panel id to display label, for the panels the manuscript carries. The order
#: of this dict is the order the prose first cites them, which is the order the
#: numbers have to run in.
MAIN_LABELS = {
    "T4d": "1",     # every declared acquisition-context feature (Methods 2.2)
    "T8": "2",      # the pre-declared rule 2 reproduction (Results 3.1)
    "T1": "3",      # the nested input ladder (Results 3.2)
    "T3": "4",      # recovery ratio against the waveform arm (Results 3.3)
    "T6a": "5",     # the horizon ladder, per-horizon (Results 3.4)
    "T4b": "6",     # waveform gain retained under matching (Results 3.5)
    "T9": "7",      # calibration (Results 3.7)
    "T10": "8",     # net benefit at the registered threshold (Results 3.8)
    "T2": "9",      # every pre-declared target and what it measured (Results 3.9)
}

#: Panel id to display label for the supplementary panels. They ship as one
#: sequence in one file, because they are one class of item.
SUPPLEMENT_LABELS = {
    "T4a": "S1",    # row 8 discrimination, arm by arm
    "T4c": "S2",    # balance, and the acquisition-propensity diagnostic
    "T4e": "S3",    # controls on the within-stratum statistic
    "T5": "S4",     # the audit family, complete at 15 tests
    "T5b": "S5",    # every declared contrast as a paired difference
    "T6b": "S6",    # the horizon ladder, trend statistics
    "T7": "S7",     # the noise floor, per arm and label
    "T3b": "S8",    # the recovery ratio under every declared denominator
    "T0": "S9",     # the cohort reconciled against the published counts
    "T8b": "S10",   # the reproduction under the published first-record protocol
    "T4f": "S11",   # the declared matching against the no-weekday sensitivity
    "T1b": "S12",   # the exploratory triage-acuity comparator
    "T11": "S13",   # what the two de-identified calendar features are worth
    "T12": "S14",   # the recovery ratio under the shared selection
    "T13": "S15",   # calibration intercept, slope and Brier
}

ID_TO_DISPLAY = {**MAIN_LABELS, **SUPPLEMENT_LABELS}

#: Panel ids in display order: the manuscript's, then the supplement's.
DISPLAY_ORDER = list(MAIN_LABELS) + list(SUPPLEMENT_LABELS)

#: Panels rendered by something other than `make_table_main.py`.
#: the corresponding check needs this to avoid reporting a real table as
#: ungenerated. Empty since the literature summary stopped shipping:
#: every remaining panel comes from the one generator.
EXTERNAL_PANELS: set[str] = set()

#: The file a supplementary panel ships in, for prose that sends a reader there.
#: One file now, so this is a constant rather than a map, and it is kept as a
#: name rather than inlined because the prose that uses it is generated.
SUPPLEMENT_FILE = {pid: "Supplementary" for pid in SUPPLEMENT_LABELS}


def display(pid: str) -> str:
    """The display label for a panel id. `T4d` becomes `1`, `T5b` becomes `S5`."""
    try:
        return ID_TO_DISPLAY[pid]
    except KeyError:
        raise KeyError(
            f"{pid!r} is not a known panel id. Add it to MAIN_LABELS or to "
            "SUPPLEMENT_LABELS deliberately; a panel with no declared display "
            "label would be rendered with whatever number happened to be "
            "convenient") from None


def reference(pid: str) -> str:
    """How the prose sends a reader to a panel, naming the file if it is not here."""
    label = display(pid)
    if pid in SUPPLEMENT_LABELS:
        return f"{SUPPLEMENT_FILE[pid]}, Table {label}"
    return f"Table {label}"


DISPLAY_TO_ID = {label: pid for pid, label in ID_TO_DISPLAY.items()}

if len(DISPLAY_TO_ID) != len(ID_TO_DISPLAY):
    raise RuntimeError(
        "two panel ids share a display label, so a prose reference to that "
        "label would be ambiguous")
